name: ventura
description: "Ventura BI mobile app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hugeicons: ^1.1.1
  flutter_dotenv: ^6.0.0
  sqflite: ^2.4.2
  path: ^1.9.1
  dio: ^5.9.0
  google_sign_in: ^7.2.0
  flutter_native_splash: ^2.4.7
  sqflite_common_ffi_web: ^1.0.1+2
  sqflite_common_ffi:
  flutter_riverpod: ^3.0.3
  fluttertoast: ^9.0.0
  fpdart: ^1.2.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  logger: ^2.6.2
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.0
  path_provider: ^2.0.0 # allows persisting cookies across app restarts



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"


# The following section is specific to Flutter packages.
flutter:
  assets:
    - .env
    - assets/images/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic

  uses-material-design: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter_native_splash:

  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/images/icon.png"
  image_dark: "assets/images/icon.png"
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true
  android_12:
    color: "#ffffff"
    image: "assets/images/icon.png"
    icon_background_color: "#ffffff"
